name: "Build container and push to ghcr"

on:
  push:
    branches:
      - senpai

  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-push-container:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/android-kernel-build-env:latest
            ghcr.io/${{ github.repository_owner }}/android-kernel-build-env:${{ github.sha }}
          labels: |
            org.opencontainers.image.description = "My container for building Android kernels"
